# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test and Lint Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout URL-Analyser
        uses: actions/checkout@v3
    - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          auto-activate-base: false
          miniconda-version: 'latest'
          python-version: "3.6.15"
          environment-file: environment.yml
          activate-environment: URLAnalyser
    - name: Lint with flake8
        run: |
          python -m flake8 . --max-line-length=120 
    - name: Test with pytest
        run: |
          python -m pytest tests/ --disable-pytest-warnings --cov=URLAnalyser -vs
